import {
    AudioPostRecordSchema,
    type AudioPostRecord,
    type AudioPostView,
    type AudioEmbed,
    type AudioEmbedView,
    type ReplyRef,
    type TranscriptEnrichmentRecord,
    type ViewerState,
} from 'shared/types/audio';
import { EMBED_NSID } from 'shared/nsid';
import type { ProfileViewBasic } from 'shared/types/views';
import type { ProcessingStageStatus } from 'shared/types/processing';
import { ForbiddenError, NotFoundError } from 'shared/errors';
import type {
    AudioPostDependencies,
    AudioPostQueryOptions,
    AudioPostThreadOptions,
} from '../ports/audio-posts-dependencies';
import { NSID } from 'shared/nsid';

/**
 * AudioPostService — CRUD + batched hydration for the Antiphony canonical
 * `dev.antiphony.audio.post` model.
 *
 * Three model rules this service enforces (documented on the lexicons docs
 * page, apps/docs/src/content/docs/lexicons/overview.md):
 *  1. `kind` is derived from `reply` presence at write time (cheap index).
 *  2. The transcript is platform enrichment, **lifted into the embed view at
 *     read time** — never stored on the canonical record.
 *  3. The stored audio is a content CID (`BlobRef.ref.$link`); the view
 *     carries a short-lived signed playback URL resolved from it.
 */

export interface CreateAudioPostInput {
    /** Multi-tenant isolation key — the origin app creating the post. */
    originAppId: string;
    /** Authoring user id. */
    authorId: string;
    /** Optional AT Protocol identity of the author. */
    authorDid?: string;
    /** Optional org context. */
    orgId?: string | null;
    /** User-authored text. May be empty for pure-audio posts. */
    text: string;
    /** Optional headline (prompt feature only). */
    title?: string;
    /** The uploaded audio attachment. */
    embed?: AudioEmbed;
    /** Present ⇒ this post is a reply (StrongRef root + parent). */
    reply?: ReplyRef;
    /** BCP-47 language tags. */
    langs?: string[];
    /** Author self-label values. */
    selfLabels?: string[];
    /**
     * Resolved initial per-stage processing status (B5), when the app opted
     * into processing. The caller (route) resolves the request against the
     * deployment's capabilities into `pending`/`skipped`; the service just
     * stamps `updatedAt` and stores it. Absent ⇒ no processing.
     */
    processing?: { transcribe?: ProcessingStageStatus; denoise?: ProcessingStageStatus };
}

/**
 * Build the canonical `at://` uri for a post: `at://{appDid}/{collection}/{rkey}`.
 *
 * The authority is the tenant's **app DID** — the repo owner under Antiphony's
 * app-as-repo-owner custody model (Model B), NOT the author. Author identity
 * (`authorId`/`authorDid`) stays on the record as attribution facets and never
 * enters the uri. Call sites resolve the app DID from `record.originAppId` via
 * `deps.getAppDid` and pass it in explicitly, so this stays a pure function of
 * (authority, rkey) with no hidden config lookup.
 *
 * Exported so the threading query and the StrongRefs handed to clients are
 * generated by the same rule.
 */
export function buildPostUri(appDid: string, rkey: string): string {
    return `at://${appDid}/${NSID.AudioPost}/${rkey}`;
}

/**
 * Extract the post id (rkey) from a post `at://` uri — the inverse of
 * `buildPostUri` — but ONLY when the uri's authority is `expectedAppDid` (the
 * caller's own tenant app DID). A StrongRef whose authority is a different app
 * DID — a forged or cross-tenant reference — returns null, so it can't resolve
 * inside another tenant. This makes explicit, at parse time, the tenancy scope
 * that `resolveReplyParticipants` otherwise enforces only via the origin-app
 * post lookup. Returns null for a malformed/empty/non-matching uri.
 */
export function parsePostId(uri: string, expectedAppDid: string): string | null {
    const AT = 'at://';
    if (!uri.startsWith(AT)) return null;
    // Segments: [authority, collection, rkey]. filter(Boolean) drops empty
    // segments so a trailing slash (or `//`) doesn't yield an empty id.
    const segments = uri.slice(AT.length).split('/').filter(Boolean);
    if (segments.length < 3) return null;
    // Authority MUST be the tenant's own app DID — reject cross-tenant/forged refs.
    if (segments[0] !== expectedAppDid) return null;
    const rkey = segments[segments.length - 1];
    return rkey && rkey.trim() ? rkey : null;
}

/**
 * Project the post's public lexicon fields into the canonical
 * `dev.antiphony.audio.post` record shape — the object whose DAG-CBOR
 * encoding the record CID is computed over.
 *
 * Rules that keep the CID deterministic and atproto-faithful:
 *  - Public lexicon fields ONLY — storage/tenancy fields (`id`,
 *    `originAppId`, `authorId`, `kind`, `threadParticipants`) never enter
 *    the hash, so re-indexing can't change a record's identity.
 *  - Absent optionals are OMITTED (never `undefined`/`null` placeholders).
 *  - `createdAt` is the ISO-8601 string, as the lexicon stores it.
 *  - `selfLabels` is expanded to the lexicon's
 *    `com.atproto.label.defs#selfLabels` union shape.
 */
export function canonicalPostRecord(input: {
    text: string;
    title?: string;
    embed?: AudioEmbed;
    reply?: ReplyRef;
    langs?: string[];
    selfLabels?: string[];
    createdAt: Date;
}): Record<string, unknown> {
    return {
        $type: NSID.AudioPost,
        text: input.text,
        ...(input.title !== undefined ? { title: input.title } : {}),
        // Field-by-field (not a spread): a spread would carry explicitly-
        // `undefined` optionals through, and DAG-CBOR encoding throws on
        // `undefined` — omission is the only valid "absent".
        ...(input.embed !== undefined
            ? {
                  embed: {
                      $type: EMBED_NSID.Audio,
                      audio: input.embed.audio,
                      ...(input.embed.durationMs !== undefined ? { durationMs: input.embed.durationMs } : {}),
                      ...(input.embed.alt !== undefined ? { alt: input.embed.alt } : {}),
                      ...(input.embed.waveform !== undefined ? { waveform: input.embed.waveform } : {}),
                  },
              }
            : {}),
        ...(input.reply !== undefined ? { reply: input.reply } : {}),
        ...(input.langs !== undefined ? { langs: input.langs } : {}),
        ...(input.selfLabels !== undefined && input.selfLabels.length > 0
            ? {
                  labels: {
                      $type: 'com.atproto.label.defs#selfLabels',
                      values: input.selfLabels.map((val) => ({ val })),
                  },
              }
            : {}),
        createdAt: input.createdAt.toISOString(),
    };
}

export class AudioPostService {
    constructor(private readonly deps: AudioPostDependencies) {}

    /**
     * Create a canonical post. Derives `kind` from `reply` presence and drops
     * `title` on replies (the record invariant forbids it). The record is
     * schema-validated before it's persisted.
     */
    async createPost(input: CreateAudioPostInput): Promise<AudioPostRecord> {
        const kind: AudioPostRecord['kind'] = input.reply ? 'reply' : 'prompt';

        // Reply gating: resolve the parent to authorize the reply and derive
        // the branch participant pair. Prompts have no parent, so they skip this.
        const threadParticipants = input.reply
            ? await this.resolveReplyParticipants(input.originAppId, input.authorId, input.reply)
            : undefined;

        const createdAt = this.deps.now();
        // Replies carry no title (record invariant); only prompts do.
        const title = kind === 'prompt' ? input.title : undefined;

        // Record CID — computed over the canonical lexicon projection (public
        // fields only) BEFORE persisting, so the stored record and every
        // StrongRef built from it carry a verifiable content address.
        const cid = await this.deps.cidForRecord(
            canonicalPostRecord({
                text: input.text,
                title,
                embed: input.embed,
                reply: input.reply,
                langs: input.langs,
                selfLabels: input.selfLabels,
                createdAt,
            }),
        );

        // Initial processing state (B5) — the caller already resolved the
        // request against deployment capabilities into per-stage
        // pending/skipped; we just stamp the clock. Storage-layer, not in the
        // CID above.
        const processing = input.processing
            ? { ...input.processing, updatedAt: createdAt }
            : undefined;

        const record = AudioPostRecordSchema.parse({
            id: this.deps.newPostId(),
            cid,
            originAppId: input.originAppId,
            authorId: input.authorId,
            authorDid: input.authorDid,
            orgId: input.orgId ?? undefined,
            kind,
            threadParticipants,
            processing,
            text: input.text,
            title,
            embed: input.embed,
            reply: input.reply,
            langs: input.langs,
            selfLabels: input.selfLabels,
            createdAt,
        });

        await this.deps.savePost(record);
        return record;
    }

    /**
     * Authorize a reply and compute its branch participant pair (§6 "Reply
     * gating"). Throws when the parent is missing/cross-tenant (404) or the
     * author isn't allowed to reply (403).
     *
     * - parent is the **prompt** (thread-root): any authenticated author may
     *   answer (the app's default audience policy); the branch opens with
     *   `{ creator (prompt author), this responder }`.
     * - parent is a **reply**: only the branch's existing participants may
     *   continue — the pair is inherited unchanged. Keying off the branch pair
     *   (not `parent.author`) is what lets the creator ↔ responder back-and-forth
     *   continue past the second turn.
     */
    private async resolveReplyParticipants(
        originAppId: string,
        authorId: string,
        reply: ReplyRef,
    ): Promise<string[]> {
        const parentId = parsePostId(reply.parent.uri, this.deps.getAppDid(originAppId));
        const parent = parentId ? await this.deps.getPostById(originAppId, parentId) : null;
        if (!parent) {
            throw new NotFoundError('Parent post not found');
        }

        if (parent.kind === 'prompt') {
            // Top-level reply: the audience answers the call. Deduped so a
            // creator replying to their own prompt collapses to a single id.
            return Array.from(new Set([parent.authorId, authorId]));
        }

        // Reply to a reply: participant-only. Inherit the established pair.
        const participants = parent.threadParticipants ?? [parent.authorId];
        if (!participants.includes(authorId)) {
            throw new ForbiddenError('Only the thread participants can reply here');
        }
        return participants;
    }

    /**
     * Fetch a single hydrated post view, scoped to `originAppId`. Returns null
     * when the post is missing or owned by a different origin app.
     */
    async getPostView(
        originAppId: string,
        id: string,
        viewerUid: string | null,
    ): Promise<AudioPostView | null> {
        const record = await this.deps.getPostById(originAppId, id);
        if (!record) return null;
        const [view] = await this.hydrateAudioPosts([record], viewerUid);
        return view ?? null;
    }

    /** List the author's posts (origin-app-scoped), hydrated. */
    async getPostsForAuthor(
        originAppId: string,
        authorId: string,
        viewerUid: string | null,
        options?: AudioPostQueryOptions,
    ): Promise<AudioPostView[]> {
        const records = await this.deps.queryByAuthor(originAppId, authorId, options);
        return this.hydrateAudioPosts(records, viewerUid);
    }

    /** List replies to a post (origin-app-scoped), hydrated in thread order. */
    async getReplies(
        originAppId: string,
        parentUri: string,
        viewerUid: string | null,
        options?: AudioPostThreadOptions,
    ): Promise<AudioPostView[]> {
        const records = await this.deps.queryReplies(originAppId, parentUri, options);
        return this.hydrateAudioPosts(records, viewerUid);
    }

    /**
     * Batched hydration (records → views). Loads all authors and transcript
     * enrichments in ONE round each (N+1 ban), then assembles per-record views:
     * lifts the transcript, signs the audio URL, and computes viewer state.
     */
    async hydrateAudioPosts(
        records: AudioPostRecord[],
        viewerUid: string | null,
    ): Promise<AudioPostView[]> {
        if (records.length === 0) return [];

        const authorIds = Array.from(new Set(records.map((r) => r.authorId)));
        // Resolve authority per-record: a hydration batch can span tenants, and
        // each record's uri is keyed on ITS tenant's app DID.
        const uris = records.map((r) => buildPostUri(this.deps.getAppDid(r.originAppId), r.id));

        const [authorMap, transcriptMap] = await Promise.all([
            this.deps.getAuthorsByIds(authorIds),
            this.deps.getTranscriptsBySubjectUris(uris),
        ]);

        return Promise.all(
            records.map((record) => this.hydrateOne(record, authorMap, transcriptMap, viewerUid)),
        );
    }

    private async hydrateOne(
        record: AudioPostRecord,
        authorMap: Map<string, ProfileViewBasic>,
        transcriptMap: Map<string, TranscriptEnrichmentRecord>,
        viewerUid: string | null,
    ): Promise<AudioPostView> {
        const uri = buildPostUri(this.deps.getAppDid(record.originAppId), record.id);

        // --- Hydrated audio embed (signed URL + lifted transcript) ---
        // Guard the nested audio ref defensively: although a parsed record with
        // an `embed` always carries `audio.ref.$link` (schema-enforced), the
        // hydrator is a read boundary that may see records from other code paths.
        const embedRecord = record.embed;
        let embed: AudioEmbedView | undefined;
        if (embedRecord?.audio?.ref?.$link) {
            // Playback resolves to the DENOISED variant once it's ready; the
            // record's own `audio.ref.$link` stays the immutable original CID.
            const proc = record.processing;
            const playbackCid =
                proc?.denoise === 'ready' && proc.denoisedBlobCid
                    ? proc.denoisedBlobCid
                    : embedRecord.audio.ref.$link;
            const signedUrl = await this.deps.signAudioUrl(record.originAppId, playbackCid);
            if (signedUrl) {
                embed = {
                    $type: 'dev.antiphony.embed.audio#view',
                    url: signedUrl,
                    durationMs: embedRecord.durationMs,
                    alt: embedRecord.alt,
                    waveform: embedRecord.waveform,
                    transcript: transcriptMap.get(uri)?.transcript,
                    // Surface per-stage processing status (no internal fields)
                    // when the app opted in; absent otherwise.
                    processing: proc
                        ? { transcribe: proc.transcribe, denoise: proc.denoise }
                        : undefined,
                };
            }
        }

        // Synthetic stub for a missing author so the view still renders, mirroring
        // the legacy reply hydrator's fallback.
        const author: ProfileViewBasic = authorMap.get(record.authorId) ?? {
            id: record.authorId,
            handle: null,
            displayName: 'Unknown User',
        };

        return {
            uri,
            cid: record.cid,
            kind: record.kind,
            author,
            record: {
                text: record.text,
                title: record.title,
                reply: record.reply,
                langs: record.langs,
                selfLabels: record.selfLabels,
                createdAt: record.createdAt,
            },
            embed,
            viewer: this.computeViewerState(record, viewerUid),
        };
    }

    /**
     * Per-viewer state: authorship + reply gating (§6). A prompt is repliable by
     * any authenticated viewer (audience-policy default); a reply only by its
     * branch participants. Anonymous viewers can't reply to anything.
     */
    private computeViewerState(record: AudioPostRecord, viewerUid: string | null): ViewerState {
        const isAuthor = viewerUid !== null && viewerUid === record.authorId;

        if (viewerUid === null) {
            return { isAuthor, canReply: false, replyDisabledReason: 'unauthenticated' };
        }
        if (record.kind === 'prompt') {
            return { isAuthor, canReply: true };
        }
        const participants = record.threadParticipants ?? [record.authorId];
        return participants.includes(viewerUid)
            ? { isAuthor, canReply: true }
            : { isAuthor, canReply: false, replyDisabledReason: 'not_a_participant' };
    }
}
